#!/bin/bash

# Some 'instance_id' do not end with the file, so I add .title to instance_id
# Some 'instance_id' include |DATA_NODE, so i remove it with sub("\\|.*"; "")
# Some 'instance_id' end with extension .nc_0 so we change it to .nc with sub("\\.nc_[0-9]+";".nc")

jq '
{
    url: .url[0]|split("|")[0],
    size,
    instance_id: (.instance_id|sub("\\|.*"; "")|sub("\\.nc_[0-9]+";".nc")|gsub("\\.(?!nc$)";"/")),
    replica,
    title,
    checksum: [(.checksum_type|first|ascii_downcase|sub("sha";"sha-")|tostring), (.checksum|first|tostring)]|join("=")
} |
if .instance_id|endswith(".nc")|not then . + {instance_id: [.instance_id, .title]|join("/")} else . end |
select(.instance_id|endswith(".nc"))' | jq -rn '
reduce inputs as $file ({}; .[$file.instance_id].urls as $u | . + {($file.instance_id): {"urls": ($u + [$file.url]), "checksum": $file.checksum}}) |
to_entries[] |
(.value.urls|unique|join("\t")),"  checksum="+.value.checksum,"  out="+.key, ""'
