#!/bin/bash

# CEDA does not support range requests and aria2c requires them, so this
# script uses curl to download the files that were not downloaded by aria

usage() {
    echo "esgf-curl [ -h ] [ -g GLOBUS_DIRECTORY ] -d DESTINATION FILE"
}

if ! command -v curl &>/dev/null; then
    echo "curl is not installed, exiting..." >&2
fi

while [[ $# -gt 0 ]]
do
    case "$1" in
    -d | --destination)
        destination="$2"
        shift 2
        ;;
    -g | --globus)
        globusdir="$2"
        shift 2
        ;;
    -h | --help)
        usage
        exit 1
        ;;
    -*)
        echo "Error: Unknown option: $1" >&2
        exit 1
        ;;
    *)
        file="$1"
        break
        ;;
    esac
done

if [ -z "$destination" ] || [ -z "$file" ]; then
    usage
    exit 1
fi

certs=""
if ! [ -z "$globusdir" ]; then
    certs="-E $globusdir/certificate-file --cacert $globusdir/certificate-file --cookie-jar cookie.txt -b cookie.txt"
fi

from_aria() {
    awk '
        /^http/{ url=$1 }
        /out=/{
            sub("  out=", "")
            if(url != "") printf "%s %s\n", $0, url
            url=""
        }' $1
}

download() {
    localpath="$1"
    url="$2"
    if ! [ -s "$localpath" ]; then
        curl $certs --insecure -L --create-dirs -o $localpath $url
    fi
}

from_aria $file | while read localpath url
do
    download "${destination}/${localpath}" "$url"
done
