package:
    name: myproxyclient
    version: 2.1.0
source:
    fn: MyProxyClient-2.1.0.tar.gz
    sha256: 0a309413dddff370f4bfc4ad30030575a4be0846afd464cf61f8164942c77241
    url: https://files.pythonhosted.org/packages/85/c4/172e5516e7e7d7338f6b6026a604f9635ba4bea6e9ed5097354b7722d714/MyProxyClient-2.1.0.tar.gz
build:
    entry_points:
        - myproxyclient = myproxy.script:main
    noarch: ''
    noarch_python: false
    number: '0'
    script: python setup.py install --single-version-externally-managed --record record.txt
    string: py27_0
requirements:
    build:
        - setuptools 33.1.1 py27_0
        - readline 6.2 0
        - zlib 1.2.11 0
        - certifi 2017.4.17 py27_0
        - openssl 1.0.2k 0
        - sqlite 3.13.0 1
        - python 2.7.13 1
        - ca-certificates 2017.1.23 1
        - ncurses 5.9 10
        - tk 8.5.19 1
    run:
        - python
        - pyopenssl
#test:
#    commands:
#        - myproxyclient --help
#    imports:
#        - myproxy
#        - myproxy.test
#        - myproxy.utils
#about:
#    home: https://github.com/cedadev/MyProxyClient
#    license: BSD 3-clause
#    license_file: myproxy/LICENSE
#    summary: MyProxy Client
extra:
    final: true
    recipe-maintainers:
        - Ezequiel Cimadevilla

