package:
  name: python-jsonrpc
  version: 0.10.0
source:
  git_url: https://github.com/gerold-penz/python-jsonrpc
  git_rev: af3216d5668bb0d4086b1de1134c69af84b3f2d0
requirements:
  build:
    - python=2
    - setuptools
    - munch
  run:
    - python=2
build:
  script: python setup.py install
